# Generated by Django 4.2.4 on 2023-12-01 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quest", "0002_alter_user_managers_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
        migrations.RemoveField(model_name="user", name="date_joined",),
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="groups",),
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="is_staff",),
        migrations.RemoveField(model_name="user", name="is_superuser",),
        migrations.RemoveField(model_name="user", name="last_login",),
        migrations.RemoveField(model_name="user", name="last_name",),
        migrations.RemoveField(model_name="user", name="user_permissions",),
        migrations.AlterModelTable(name="vote", table="vote_question",),
        migrations.CreateModel(
            name="VoteAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quest.answer"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quest.user"
                    ),
                ),
            ],
            options={"db_table": "vote_answer",},
        ),
    ]
